# Data manipulation

## 2.1.1 shape & reshape

In [ ]:
from re import X
import tensorflow as tf

x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

通过`shape`属性可以查看张量tensor的形状, 通过`reshape`可以变换tensor的形状。虽然张量的形状发生了改变，但其元素值并没有变。

In [ ]:
print('Original shape: ', x.shape)
print('Transformed shape: \n', tf.reshape(x, (3, 4)))

Original shape:  (12,)
Transformed shape: 
 tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)


<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

手动指定tensor的高度和宽度很费事，所以可以使用-1来代替行或者列，另外一个属性只要指定之后，就可以自动计算出新的tensor尺寸。

In [ ]:
# -1代替指定高度，而知道是3列，所以自然就会计算出是4行
tf.reshape(x, (-1, 3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

创建多维张量

In [ ]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

创建随机值填充矩阵

In [ ]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.81721973, -1.2987093 ,  0.44348294,  1.3539954 ],
       [ 0.0187675 ,  0.40118602, -0.89959794, -1.3285049 ],
       [ 1.1306841 , -0.28963134, -0.6543195 , -2.7716243 ]],
      dtype=float32)>

为元素赋予常量值

In [ ]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

## 2.1.2 运算符

In [24]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y, tf.exp(x) # exp() 求幂

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=
 array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
       dtype=float32)>)

张量连结concatenation, `axis=0`是按行连结，`axis=1`是按列连结。

In [35]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# 进行张量连结
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1), X == Y, tf.reduce_sum(X), tf.reduce_sum(Y)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])>,
 <tf.Tensor: shape=(), dtype=float32, numpy=66.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.0>)

## 2.1.3 广播机制
在上面的部分中，我们看到了如何在相同形状的两个张量上执行按元素操作。 在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。
1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。

In [41]:
a = tf.reshape(tf.range(6), (6, 1)) # 复制列
b = tf.reshape(tf.range(4), (1, 4)) # 复制行
a, b, a + b

(<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]], dtype=int32)>,
 <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[0, 1, 2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7],
        [5, 6, 7, 8]], dtype=int32)>)

## 2.1.4 索引和切片

In [44]:
c = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
c[-1], c[1:3]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

## 2.1.5 转换为其他python对象

In [46]:
# 转换tensor到Numpy array
A = c.numpy()
B = tf.constant(A)
type(A), type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。
要使用`item()`必须要转成`numpy`或者是python标准类型

In [49]:
d = tf.constant([3.5]).numpy()
d, d.item(), float(d), int(d)

<ipython-input-49-81cc17da103f>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  d, float(d), int(d)


(array([3.5], dtype=float32), 3.5, 3)