# 2.3 线性代数

## 2.3.1 标亮
严格来说，仅包含一个数值被称为标量（scalar）

In [ ]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x - y, x * y, x / y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000))

## 2.3.2 向量
向量可以被视为标量值组成的列表。 这些标量值被称为向量的元素（element）或分量（component）。
通过一维张量表示向量。一般来说，张量可以具有任意长度，取决于机器的内存限制。

In [ ]:
vector = torch.arange(4)
vector, vector[3], len(vector), vector.shape

(tensor([0, 1, 2, 3]), tensor(3), 4, torch.Size([4]))

## 2.3.3 矩阵
当调用函数来实例化张量时， 我们可以通过指定两个分量m和n
来创建一个形状为m * n的矩阵。

In [ ]:
aMatrix = torch.arange(20).reshape(5, 4)
aMatrix, aMatrix.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

作为方阵的一种特殊类型，对称矩阵（symmetric matrix），矩阵本身等于其对称矩阵

In [ ]:
bMatrix = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
bMatrix, bMatrix == bMatrix.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

## 2.3.4 张量 - n维数组
张量是描述具有任意数量轴的n维数组的通用方法。   
当我们开始处理图像时，张量将变得更加重要，图像以n维数组形式出现， 其中3个轴对应于高度、宽度，以及一个通道（channel）轴， 用于表示颜色通道（红色、绿色和蓝色）。

In [ ]:
aTensor = torch.arange(24).reshape(2, 3, 4)
aTensor

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 2.3.5 张量算法的一元、二元运算
从按元素操作的定义中可以注意到，任何按元素的一元运算都不会改变其操作数的形状。 同样，给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量。 例如，将两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法。

In [ ]:
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
B = A.clone()
A, B, A == B, A + B, A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.]]))

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 2.3.6 降维 (求和的方式)
我们可以对任意张量进行的计算其元素的和, 计算元素的和这个方式实际上就是在体现降维。   
默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。   
我们还可以指定张量沿哪一个轴来通过求和降低维度。以矩阵为例，为了通过**求和所有行**的元素来降维（轴0），可以在调用函数时指定axis=0。 如果是求和所有列，那么就是轴1，指定axis=1即可。   

**可以理解成axis=0的时候就是把行压扁，竖着求和**。


In [ ]:
x = torch.arange(12).reshape(3, 4)
# A = torch.arange(24).reshape(2, 3, 4)
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
# 按照行来求和
A_sum_axis0 = A.sum(axis=0)
B_sum_axis1 = A.sum(axis=1)
x, x.sum(), A, A.sum(), A_sum_axis0, A_sum_axis0.shape, B_sum_axis1, B_sum_axis1.shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor(66),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor(190.),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

In [ ]:
A.mean(), A.sum()/A.numel(), A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor(9.5000),
 tensor(9.5000),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]))

## 2.3.7 点积
实现点积有两种方式:
1. 通过使用`torch.dot()`来实现点积
2. 通过使用`*`符号进行元素乘法再进行`sum()`求和

In [38]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
# x.dot(y)
torch.dot(x, y), sum(x * y)

(tensor(6.), tensor(6.))