# Numpy
## 算术运算
Numpy的算术运算

In [9]:
import numpy as np


a = np.array([[1,2],[3,4]])
b = np.array([[3,0],[0,6]])

# 这样是逐元素相乘，而不是矩阵点乘
print("a * b: ", a * b, "\n")

# 矩阵点乘
print("a dob b: ", np.dot(a, b), "\n")

c = np.array([[1,2,3],[4,5,6]])
print("c: ", c * 10)

a * b:  [[ 3  0]
 [ 0 24]] 

a dob b:  [[ 3 12]
 [ 9 24]] 

c:  [[10 20 30]
 [40 50 60]]


## 广播
NumPy中，形状不同的数组之间也可以进行运算。在2×2 的矩阵A和标量10之间进行了乘法运算，标量10被扩展成了2 × 2 的形状，然后再与矩阵A进行乘法运算，这个巧妙的功能称为广播（broadcast）。

In [12]:
A = np.array([[1,2], [3,4]])
B = np.array([[10, 20]])

print("A * B: ", A * B)

A * B:  [[10 40]
 [30 80]]


## 访问元素

In [22]:
X = np.array([[51, 55], [14, 19], [0, 4]])
# 循环访问X的每一行
for row in X:
    print(row)

# 根据索引访问X的元素
print(X[0][1])

# 使用数组访问X的元素
X = X.flatten()
print(X)
print(X[np.array([0, 2, 4])])
print(X[X > 15])

[51 55]
[14 19]
[0 4]
55
[51 55 14 19  0  4]
[51 14  0]
[51 55 19]
